// import { parse } from 'node-html-parser';
// const parse = require('node-html-parser').parse;

const sample = `<li data-id="128629489" data-author="los palavros" data-author-id="1399469" data-flags="share msg report vote entrymodlog favorite" data-isfavorite="false" data-ispinned="false" data-favorite-count="2" data-seyler-slug="" data-comment-count="0">   <div class="content content-expanded">     çünkü adam <a class="b" href="/?q=yat">yat</a>mış.<br><br>(yat, suda giden yat)   </div>   <footer>     <div class="feedback"><span class="share-links"><a target="_blank" rel="nofollow noopener" href="http://www.facebook.com/sharer.php?u=https%3A%2F%2Feksisozluk.com%2Fentry%2F128629489&amp;p[title]=adam%C4%B1n%20biri%20denize%20d%C3%BC%C5%9Fm%C3%BC%C5%9F%20batmam%C4%B1%C5%9F%20neden&amp;p[summary]=%0A%20%20%20%20%C3%A7%C3%BCnk%C3%BC%20adam%20yatm%C4%B1%C5%9F.(yat%2C%20suda%20giden%20yat)%0A%20%20&amp;p[images][0]=https://eksisozluk.com/content/img/ilogo_fbv2.png&amp;v=1" aria-label="facebook" title="facebook" class="svgico svgico-facebook"><svg class="eksico" id="svg-icon-facebook">     <use xlink:href="#eksico-icon-facebook"></use>   </svg></a><a target="_blank" rel="nofollow noopener" href="/entry/tweet/128629489" aria-label="twitter" title="twitter" class="svgico svgico-twitter"><svg class="eksico" id="svg-icon-twitter">     <use xlink:href="#eksico-icon-twitter"></use>   </svg></a></span><span class="rate-options"><a class="like" title="şükela!"><span></span><svg class="eksico" id="svg-chevron-up">     <use xlink:href="#eksico-chevron-up-thick"></use>   </svg></a><a class="dislike" title="çok kötü"><span></span><svg class="eksico" id="svg-chevron-down">     <use xlink:href="#eksico-chevron-down-thick"></use>   </svg></a></span><span class="favorite-links" style="">   <a class="favorite-link" title="favorilere ekle" aria-label="favorilere ekle"><svg class="eksico"><use xlink:href="#eksico-drop"></use></svg></a>   <a class="favorite-count toggles">2</a>   <div class="favorite-list-popup toggles-menu"><div></div></div> </span></div>     <div class="info">        <a class="entry-date permalink" href="/entry/128629489">01.10.2021 19:08</a>              <a class="entry-author" href="/biri/los-palavros">los palavros</a>     <div class="other dropdown"><a class="dropdown-toggle toggles" title="diğer"><svg class="eksico" id="svg-dots">     <use xlink:href="#eksico-dots"></use>   </svg></a><ul class="dropdown-menu right toggles-menu"><li><a title="mesaj gönder" aria-label="mesaj gönder">mesaj gönder</a></li><li><a class="report-link" title="aynen öyle" href="/iletisim?RefEntryId=128629489&amp;Category=Content&amp;Subject='adam%C4%B1n%20biri%20denize%20d%C3%BC%C5%9Fm%C3%BC%C5%9F%20batmam%C4%B1%C5%9F%20neden'%20ba%C5%9Fl%C4%B1%C4%9F%C4%B1ndaki%20%23128629489%20no'lu%20entry">şikayet</a></li><li><a href="/modlog?q=%23128629489">modlog</a></li><li><a href="#">engelle</a></li></ul></div></div>   </footer>   <div class="comment-summary">   <div class="comment-pages">   </div> </div> </li>`
// const sample = '<ul id="list"><li>Hello World</li></ul>';
// const html2entry = (html) => {
//     const root = parse(html);
//
//     const attr = root.
//
//     console.log(attr);
// };
